export const publisher={name:'WickWorks',email:'jakenftwick@gmail.com',site:'onlysubs.wickworks.app',version:'2026-09-08',country:'Philippines'}
export const policies={
 privacy:{title:'Privacy notice',sections:[
 ['Who operates onlysubs','WickWorks operates onlysubs from the Philippines as a free portfolio video-clipping application. Contact jakenftwick@gmail.com for privacy requests. WickWorks is the supplied brand name; formal legal operator details and hosting disclosures are still being finalized. These are review-stage notices, not a claim of legal compliance.'],
 ['Philippine privacy rights','The Philippine Data Privacy Act of 2012 and applicable National Privacy Commission rules may govern personal data processed by the publisher. You may contact us about your rights to be informed, access, object, correct, erase or block, and data portability where applicable. You can raise a complaint with the National Privacy Commission at privacy.gov.ph. Rights, exceptions, and applicable obligations depend on the actual processing.'],
 ['Your videos stay on your device','The desktop app processes imported videos, extracted audio, transcripts, selections, previews, and exports on your computer. WickWorks does not receive that media through the app. Imports are local copies; your original file is not changed. Files are not encrypted by onlysubs: protect your Windows account, disk, and backups.'],
 ['What is saved','Project edits and job records are saved in the application data folder to support recovery. An optional browser backup stores a second draft on the device. Settings, your first-run acceptance, and the backup preference are local. Generated files remain until you delete them. Manage storage removes selected generated exports, not separate copies in Downloads.'],
 ['Network connections','The initial speech-model download may connect to the model provider and disclose your IP address and normal connection information. Optional Ollama runs on loopback; onlysubs rejects remote Ollama addresses and redirects. Locally installed dependencies may have their own network behavior. The public website host may process access and security logs, including IP addresses and browser information. Hosting service, log retention, and processor details must be confirmed before public launch.'],
 ['Support, choices, and rights','Emailing support sends your address, message, and attachments to the publisher and email provider. Do not send private footage, passwords, or sensitive personal information. We use support messages to respond and resolve issues; a retention period must be finalized before public launch. Depending on applicable law, you may request access, correction, deletion, objection, restriction, or portability and complain to your regulator. Identity checks may be necessary; we cannot remotely delete files held only on your device.'],
 ['Young users','This release is intended for ages 13 and above, not children under 13. Users who are minors should involve a parent or guardian. A minimum age is not a substitute for legally required parental consent. We do not ask for a birth date or create accounts. Contact us if you believe a child has sent personal information.'],
 ['Voluntary support','The website may link to WickWorks\' GitHub Sponsors profile. GitHub operates that external payment service under its own terms and privacy notice. onlysubs does not receive your videos, transcripts, or editing data through a contribution, and contributions do not grant access to personal data.'],
 ['Changes','Material changes to processing or optional third-party features require an updated notice and, where required, a new choice before activation. No advertising, analytics SDK, tracking pixel, or third-party embed is currently included.']
 ]},
 terms:{title:'Terms & desktop licence',sections:[
 ['Free portfolio release','onlysubs is an experimental, free video editor provided by WickWorks in the Philippines for users aged 13+. You may install and use the application for lawful personal or commercial editing. Third-party components remain subject to their own licences. These review-stage terms need legal review before public release. If you are under 18, ask your parent or guardian to review and accept these terms with you.'],
 ['Your content and permission','You keep ownership of your media and edits. Use footage, recordings, music, fonts, and images only when you have the necessary rights or another lawful basis. Consider the privacy and consent of people recorded, including minors. The app does not grant permission to repost someone else’s work.'],
 ['Review AI output','Transcripts, timing, crop choices, and clip suggestions can be incorrect or misleading. Review the full result before publication. No guarantee is made about accuracy, audience growth, platform acceptance, or identical export quality. Burning captions requires re-encoding.'],
 ['Responsible use','Do not use onlysubs for unlawful surveillance, non-consensual intimate imagery, child exploitation, harassment, fraud, impersonation, or copyright infringement. Do not remove safeguards to access another person’s computer or information.'],
 ['Availability and responsibility','Keep backups of important originals and projects. The application can fail or be interrupted; automatic saving does not guarantee recovery of every operation. This experimental release is provided without promises of uninterrupted or error-free service, to the extent permitted by law. Nothing excludes mandatory consumer rights or liability that cannot legally be excluded. No subscription or payment is required for this release.'],
 ['Permanent Free tier and voluntary support','Core local transcription, caption editing, manual clipping, combined clips, full-video exports, previews, and storage tools remain free. Optional paid features may be offered later; these core features do not require payment or a subscription. The website may offer optional GitHub Sponsors contributions. A contribution is voluntary and does not create a subscription, purchase, service-level commitment, support priority, or entitlement to future features.'],
 ['Updates and contact','The installed Windows app checks GitHub for updates at startup and through Help. GitHub receives your IP address and normal request information; videos and transcripts are not sent in update requests. Downloads require your agreement and install when you close the app. Offline use continues if checks fail. The portable 0.3.0 version requires a one-time installer download to enable updates. Contact jakenftwick@gmail.com with questions. Applicable mandatory rights remain unaffected.']
 ]},
 cookies:{title:'Cookies & local storage',sections:[
 ['No tracking banner','The app and static product pages do not add advertising cookies, analytics, tracking pixels, or third-party embeds. We do not display a misleading Accept all banner for trackers that do not exist. Hosting-level cookies or security services must be checked on the final production domain.'],
 ['Desktop storage','onlysubs-consent-v1 stores first-run terms acknowledgement and onlysubs-backup stores your backup preference. These device-local records support your requested settings. If enabled, reel-editor-v2 contains a project draft including paths and transcript text. These are localStorage entries, not uploaded analytics. Server-side local project files are separate from browser backup.'],
 ['Your choices','Browser draft backup is off unless you enable it. Turn it off to remove its existing browser copy; disk project records remain for recovery. Clearing browser data removes local browser preferences but does not remove imported videos or exports on disk.'],
 ['Future features','Any future non-essential tracking or third-party embed must remain disabled until an appropriate, freely given choice is made where required. Reject and withdrawal controls must be as easy to use as acceptance. No consent to future tracking is requested here.']
 ]},
 accessibility:{title:'Accessibility statement',sections:[
 ['Our target','We aim toward WCAG 2.2 Level AA. This is a development target, not a certification or a claim that every criterion has passed an independent audit.'],
 ['Available controls','The editor supports keyboard controls, visible focus, labelled form inputs, status and progress messages, editable transcripts, adjustable captions, and subtitle downloads. Dialogs contain focus and return it when closed. Browser zoom and system high-contrast settings should remain available.'],
 ['Known limitations','AI captions can be inaccurate, descriptions of visual-only information are not generated, and rendered video text alone does not make all media accessible. Native media controls vary between browsers. Screen-reader and assistive-technology testing across supported Windows setups remains a release task.'],
 ['Report a barrier','Email jakenftwick@gmail.com with the page or control, assistive technology, and what happened. Do not attach private footage unless it is necessary and you are comfortable sharing it. We will review reports; no fixed response deadline is promised.']
 ]},
 security:{title:'Security & responsible use',sections:[
 ['Local boundaries','The packaged desktop server binds only to loopback and requires a per-launch secret supplied by Electron. Renderer Node access is disabled, sandboxing is enabled, external navigation and permissions are blocked, and the production app uses a restrictive content policy. These safeguards reduce risk; they are not a guarantee against all attacks.'],
 ['Safe media handling','Import only media you trust. Imports have an 8 GB limit and must fit available storage. The all-in-one release includes FFmpeg, a Python runtime, and faster-whisper; obtain updates only from the verified release page. Media decoders can have vulnerabilities; this release has not received an independent penetration test.'],
 ['Report privately','Send a minimal description to jakenftwick@gmail.com. Do not include secrets, private media, or exploit anyone else’s data. No bug bounty or guaranteed response time is offered.'],
 ['Release integrity','The initial Windows package is unsigned unless the download page explicitly states otherwise. Compare its published SHA-256 checksum. Do not turn off antivirus or device security to run it. Code signing and clean-machine testing are required before calling the release production-ready.']
 ]},
 'open-source':{title:'Third-party notices',sections:[
 ['Application components','The Windows package uses Electron (MIT), React and React DOM (MIT), plus Electron’s bundled Chromium and Node.js components with their respective notices. Full available licence texts accompany the release in THIRD-PARTY-NOTICES.txt and Electron’s LICENSES.chromium.html.'],
 ['Included processing tools','The all-in-one release bundles FFmpeg/ffprobe 9.0.1 GPL build, a Python runtime, faster-whisper, CTranslate2, PyAV, tokenizers, and supporting packages. Their licences and notices accompany the release. Speech-model weights download separately on first use under their model licence. Ollama is optional and not bundled. FFmpeg corresponding-source and build information must accompany public distribution.'],
 ['No implied affiliation','onlysubs is a WickWorks portfolio project and is not affiliated with CapCut, WayinVideo, or the dependency publishers. Caption styles are generic presets, not proprietary templates copied from those products. The onlysubs brand has not undergone trademark clearance.']
 ]}
}
