import fs from 'node:fs/promises'
import path from 'node:path'
import {policies,publisher} from '../shared/policies.mjs'
const root=path.resolve('site'),publicRelease=process.argv.includes('--public-release'),out=publicRelease?path.resolve('outputs/website'):path.join(root,'dist')
await fs.mkdir(out,{recursive:true})
for(const name of ['index.html','site.css','demo.js'])await fs.copyFile(path.join(root,name),path.join(out,name))
if(!publicRelease){const html=await fs.readFile(path.join(out,'index.html'),'utf8');await fs.writeFile(path.join(out,'index.html'),html.replace('<a id="download-link" class="button primary" href="downloads/onlysubs-0.2.0-windows-x64.exe" download>Download Windows preview ↓</a>','<button class="button" disabled>Public download not published yet</button><p class="small">The Windows preview is supplied separately to the project owner. Public distribution will follow release review.</p>').replace('<a class="text-link" href="downloads/SHA256SUMS.txt">Check SHA-256</a>',''))}
await fs.copyFile('public/onlysubs-logo.png',path.join(out,'onlysubs-logo.png'))
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const shell=(title,body)=>`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} — onlysubs</title><link rel="stylesheet" href="site.css"><link rel="icon" href="onlysubs-logo.png"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="./">onlysubs <span>by WickWorks</span></a><a href="./#download">Windows app</a></header><main id="main" class="policy"><h1>${escape(title)}</h1>${body}</main><footer><a href="./">Back to onlysubs</a><a href="mailto:${publisher.email}">Contact WickWorks</a></footer></body></html>`
for(const [key,page] of Object.entries(policies))await fs.writeFile(path.join(out,key+'.html'),shell(page.title,`<p>Updated ${publisher.version} · Review-stage notice</p>`+page.sections.map(([h,p])=>`<section><h2>${escape(h)}</h2><p>${escape(p)}</p></section>`).join('')))
await fs.writeFile(path.join(out,'setup.html'),shell('Windows setup',`<p>Free unsigned preview for Windows 10/11 x64. The app does not bundle video or speech engines.</p><h2>1. Download and check</h2><p>Download the executable and SHA256SUMS.txt. Use Windows PowerShell Get-FileHash on your download and compare SHA-256. Keep Windows security enabled. Do not run a file you cannot verify or do not trust.</p><h2>2. Install local engines</h2><p>Install FFmpeg and ffprobe from a trusted build linked by <a href="https://ffmpeg.org/download.html" rel="noreferrer">FFmpeg</a>. Install Python from <a href="https://www.python.org/downloads/windows/" rel="noreferrer">python.org</a>, then install faster-whisper into a dedicated Python environment. Setup downloads may connect to package and model providers. The desktop Settings panel accepts executable paths; restart the app after changing your Windows PATH.</p><pre>py -m venv onlysubs-engines\nonlysubs-engines\\Scripts\\python.exe -m pip install faster-whisper</pre><p>Set pythonPath to the full path to that environment’s Scripts\\python.exe. Set ffmpegPath and ffprobePath to their executable locations. Save and check engines.</p><h2>3. Edit locally</h2><p>Choose a video. Manual cuts and exports require FFmpeg; transcription also requires faster-whisper. The first transcription downloads a model and may take several minutes. Optional Ollama improves clip suggestions but is not required. Review captions, render a preview, then export. Keep the PC awake during a job.</p><h2>Saved files and removal</h2><p>Packaged app data lives under %APPDATA%\\onlysubs, or a migrated local-reel-studio folder. The desktop app is portable, but its saved data is not stored beside the EXE. Manage storage deletes selected generated exports, not original footage or copies in Downloads. To remove all app data, close the app, back up what you need, and use File Explorer to inspect and remove only its application-data folder. Do not delete your entire AppData directory.</p><h2>Known limits</h2><p>CPU transcription can be slow. HDR export is not supported. Original-size export preserves dimensions but captions require lossy re-encoding. A crash or sleep may interrupt processing; saved edits are recovered, but interrupted work must be restarted. Signing, clean-PC testing, and final legal/hosting review are pending.</p>`))
const csp="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"
await fs.writeFile(path.join(out,'_headers'),`/*\n  Content-Security-Policy: ${csp}\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n`)
await fs.writeFile(path.join(out,'.htaccess'),`<IfModule mod_headers.c>\nHeader always set Content-Security-Policy "${csp}"\nHeader always set X-Content-Type-Options "nosniff"\nHeader always set Referrer-Policy "no-referrer"\nHeader always set Permissions-Policy "camera=(), microphone=(), geolocation=()"\n</IfModule>\nOptions -Indexes\n`)
console.log('Built standalone static site: '+out)
