import fs from 'node:fs/promises'
import path from 'node:path'
import {policies,publisher} from '../shared/policies.mjs'
const root=path.resolve('site'),publicRelease=process.argv.includes('--public-release'),out=publicRelease?path.resolve('outputs/website'):path.join(root,'dist')
await fs.mkdir(out,{recursive:true})
for(const name of ['index.html','site.css','demo.js'])await fs.copyFile(path.join(root,name),path.join(out,name))
const html=await fs.readFile(path.join(out,'index.html'),'utf8')
const releaseLink='https://github.com/0xMrw1ck/onlysubs/releases/latest/download/onlysubs-0.3.0-windows-x64.exe'
await fs.writeFile(path.join(out,'index.html'),html.replace(/href="downloads\/onlysubs-0\.3\.0-windows-x64\.exe"/g,`href="${releaseLink}"`).replace(/href="downloads\/SHA256SUMS\.txt"/g,'href="https://github.com/0xMrw1ck/onlysubs/releases/latest/download/SHA256SUMS.txt"'))
await fs.copyFile('public/onlysubs-logo.png',path.join(out,'onlysubs-logo.png'))
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const shell=(title,body)=>`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} — onlysubs</title><link rel="stylesheet" href="site.css"><link rel="icon" href="onlysubs-logo.png"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="./">onlysubs <span>by WickWorks</span></a><a href="./#download">Windows app</a></header><main id="main" class="policy"><h1>${escape(title)}</h1>${body}</main><footer><a href="./">Back to onlysubs</a><a href="mailto:${publisher.email}">Contact WickWorks</a></footer></body></html>`
for(const [key,page] of Object.entries(policies))await fs.writeFile(path.join(out,key+'.html'),shell(page.title,`<p>Updated ${publisher.version} · Review-stage notice</p>`+page.sections.map(([h,p])=>`<section><h2>${escape(h)}</h2><p>${escape(p)}</p></section>`).join('')))
await fs.writeFile(path.join(out,'setup.html'),shell('Windows quick start',`<p>Free unsigned all-in-one preview for Windows 10/11 x64. Video export and speech-transcription engines are included.</p><h2>1. Download and check</h2><p>Download the executable and SHA256SUMS.txt. Use Windows PowerShell Get-FileHash on your download and compare SHA-256. Keep Windows security enabled. Do not run a file you cannot verify or do not trust.</p><h2>2. Open onlysubs</h2><p>Run the portable executable. No installer, Python, FFmpeg, terminal, account, or subscription is required. Windows may warn because this preview is not code-signed; do not disable Windows security.</p><h2>3. Transcribe or cut</h2><p>Choose a video and use manual cuts immediately. On the first transcription, onlysubs downloads your selected speech model into its local app-data folder. The recommended multilingual small model is about 486 MB. This is the only required network download after installing the app. Optional Ollama can improve clip suggestions but is not required.</p><h2>Saved files and removal</h2><p>Packaged app data lives under %APPDATA%\\onlysubs, or a migrated local-reel-studio folder. The desktop app is portable, but its saved data and downloaded speech model are not stored beside the EXE. Manage storage deletes selected generated exports, not original footage, speech models, or copies in Downloads. To remove all app data, close the app, back up what you need, and use File Explorer to inspect and remove only its application-data folder. Do not delete your entire AppData directory.</p><h2>Known limits</h2><p>The all-in-one file is larger because the processing engines are included. CPU transcription can be slow. HDR export is not supported. Original-size export preserves dimensions but captions require lossy re-encoding. A crash or sleep may interrupt processing; saved edits are recovered, but interrupted work must be restarted. Signing, clean-PC testing, and final legal/hosting review are pending.</p>`))
const csp="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"
await fs.writeFile(path.join(out,'_headers'),`/*\n  Content-Security-Policy: ${csp}\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: no-referrer\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n`)
await fs.writeFile(path.join(out,'.htaccess'),`<IfModule mod_headers.c>\nHeader always set Content-Security-Policy "${csp}"\nHeader always set X-Content-Type-Options "nosniff"\nHeader always set Referrer-Policy "no-referrer"\nHeader always set Permissions-Policy "camera=(), microphone=(), geolocation=()"\n</IfModule>\nOptions -Indexes\n`)
console.log('Built standalone static site: '+out)
